### ISSUE TITLE
Add dependency management

### ISSUE THREAD

**Issue by Nicolas-Ferre** [Nicolas-Ferre/wgso#20]
Add configuration file to automatically retrieve dependencies.

The `wgso.yaml` configuration file has the following format:
```yaml
dependencies:
  dep1:
    path: ../deps/  # relative to project folder
  dep2:
    url: https://github.com/orga/project/archive/refs/heads/main.zip # only zip format is supported
```

The library is retrieved from `<path>/<dependency name>`.
Recursive dependencies will not supported (at least for now).

When using `wgso run` command, a `_` folder is created in the project folder and contains one sub-folder per dependency.
Then the dependencies can be imported in the project:
```wgsl
#import _.dep1.mod
#import _.dep2.mod
```
